id: P006746
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01513
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༣ ༼༡༢༽
  author: ''
  volumes:
    af50dec6f9214ddca09771ad44b7368e:
      image_group_id: I5813
      title: ''
      volume_number: 1
      total_pages: 257
